title: <p align = "center"> Somnath Banerjee </p>
logo: /assets/img/me.png
description: Free thinker and Data Science enthsiast. Data analyst at PwC.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
